sudo: required

services:
  - docker

env:
  matrix:
    - PANDOC_VERSION=2.7.2
    - PANDOC_VERSION=2.7.3

script:
  - make "pandoc$PANDOC_VERSION"
  - chmod --recursive a+wrx .
  - >
    docker run
    -it
    --volume $(pwd):/home/dev/doc:rw
    --user dev
    "pandoc-container:$PANDOC_VERSION"
    bash ./test.sh
